version: "3.8"

volumes:
  storage:

services:
  storage:
    env_file: .env.dev
    extends:
      file: docker-compose.dev.yml
      service: storage

  client_bot:
    env_file: .env.dev
    build:
      dockerfile: Dockerfile.dev
    extends:
      file: docker-compose.dev.yml
      service: client_bot