version: "3.8"

volumes:
  storage:

services:
  storage:
    extends:
      file: docker-compose.main.yml
      service: storage

  client_bot:
    extends:
      file: docker-compose.main.yml
      service: client_bot