version: "3.8"

volumes:
  storage_prod:

services:
  static:
    image: nginx
    volumes:
      - ./Static/nginx.conf:/etc/nginx/nginx.conf
      - ./Static/ssl/www_mindefy_space_2023_09_19.crt:/etc/nginx/ssl/mindefy.space.crt
      - ./Static/ssl/www_mindefy_space_2023_09_19.key:/etc/nginx/ssl/mindefy.space.key
      - ./Static/html:/usr/share/nginx/html
      - ./Static/css:/usr/share/nginx/html/css
      - ./Static/js:/usr/share/nginx/html/js
      - ./Static/icon:/usr/share/nginx/html/icon
    ports:
      - "80:80"
      - "443:443"

  storage:
    image: "bitnami/mongodb:6.0.4"
    ports:
      - "27017:27017"
    env_file:
      - .env.prod
    volumes:
      - "storage_prod:/bitnami/mongodb"
    environment:
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=storage

  client_bot:
    build:
      context: ./Services/Client/Bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - STORAGE_DB_NAME=positive_db
