version: 2.1
jobs:
  deploy-production:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            ssh -i $PRIVATE_SSH_KEY $PROD_REMOTE_USER@$PROD_REMOTE_HOST \<< EOF
            cd ~/mindefy_api
            git checkout master
            git pull
            docker compose -f docker-compose.prod.yml up -d
            EOF
  deploy-dev:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Deploy to dev
          command: |
            ssh -i $SSH_KEY $REMOTE_USER@$REMOTE_HOST \<< EOF
            cd ~/mindefy_api
            git checkout dev
            git pull
            docker compose -f docker-compose.dev.yml up -d
            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
      - deploy-dev:
          filters:
            branches:
              only: dev

