version: 2.1
jobs:
  deploy-production:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e7:e5:aa:f8:6c:e9:08:e5:7f:1c:ec:b6:b1:6b:e6:72"
      - run:
          name: Deploy to production
          command: |
            ssh -i $PROD_REMOTE_USER@$PROD_REMOTE_HOST \<< EOF
            cd ~/mindefy_api
            git checkout master
            git pull
            docker compose -f docker-compose.prod.yml up -d
            EOF
  deploy-dev:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - run:
          name: Deploy to dev
          command: |
            ssh -i $REMOTE_USER@$REMOTE_HOST \<< EOF
            cd ~/mindefy_api
            git checkout dev
            git pull
            docker compose -f docker-compose.dev.yml up -d
            EOF
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
      - deploy-dev:
          filters:
            branches:
              only: dev

